services:
  app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel-app:/var/www/html
      - node_modules:/var/www/html/node_modules  # Ensure node_modules is excluded from host
    working_dir: /var/www/html
    networks:
      - laravel
    ports:
      - "8000:9000"  # PHP-FPM runs on port 9000 inside the container
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  directus-db:
    image: mysql:8.0
    container_name: mysql-directus-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: directus
      MYSQL_PASSWORD: root
    volumes:
      - directus_dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - laravel
    ports:
      - "6379:6379"

  directus:
    image: directus/directus:latest
    container_name: directus
    environment:
      KEY: "your_secret_key"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "password123"
      DB_CLIENT: "mysql"
      DB_HOST: "mysql-directus-db"
      DB_PORT: 3306
      DB_DATABASE: "directus"
      DB_USER: "root"
      DB_PASSWORD: "root"
    volumes:
      - ./directus:/var/lib/directus
    ports:
      - "8055:8055"
    depends_on:
      - directus-db
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_HOSTS: directus-db:3306  # Add this line to include the second MySQL server
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
      - directus-db
    networks:
      - laravel

volumes:
  dbdata:
  directus_dbdata:
  node_modules:  # Named volume to isolate node_modules

networks:
  laravel:
